version: '3'

services:
  # mysql:
  #   image: mysql/mysql-server:5.7
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_DATABASE=dgc
  #     - MYSQL_ROOT_PASSWORD=admin # do not use this for production deployments
  #     - MYSQL_USER=dgc_adm
  #     - MYSQL_PASSWORD=admin # do not use this for production deployments
  #   networks:
  #     persistence:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - PGPASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      persistence:

  ddcc-gateway:
    build: .
    #image: world-health-organization/ddcc-gateway
    image: smarttrustnetworkgateway:latest
    volumes:
      - ./certs:/ec/prod/app/san/dgc
      - ./logs:/logs
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=log2console,local
      #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dgc
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_JNDI_NAME=false
      - SPRING_JPA_DATABASEPLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin # do not use this for production deployments
      - DGC_TRUSTANCHOR_KEYSTOREPATH=/ec/prod/app/san/dgc/ta.jks
      - DGC_TRUSTANCHOR_KEYSTOREPASS=dgcg-p4ssw0rd # do not use this for production deployments
      - DGC_TRUSTANCHOR_CERTIFICATEALIAS=dgcg_trust_anchor
      - DGC_FEDERATION_KEYSTOREPATH=/ec/prod/app/san/dgc/ta.jks #TODO: change to federation.jks
      - DGC_FEDERATION_KEYSTOREPASSWORD=dgcg-p4ssw0rd # do not use this for production deployments
    depends_on:
    #  - mysql
      - postgres
    networks:
      backend:
      persistence:

networks:
  persistence:
  backend:
