apiVersion: v1
kind: Service
metadata:
  labels:
    app: ddcc-gateway-postgres
  name: ddcc-gateway-postgres
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ddcc-gateway-postgres
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8090
