apiVersion: v1
kind: Service
metadata:
  name: ddcc-gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ddcc-gateway
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
